export const BFF_ENDPOINTS = {
  AUTH_001: '/auth/login',
  AUTH_002: '/auth/mfa',
  AUTH_003: '/auth/otp',
  AUTH_004: '/auth/new-password',
  AUTH_005: '/auth/session',
  AUTH_006: '/auth/logout',
  AUTH_007: '/auth/refresh',
  ONBOARDING_001: '/onboarding/consent',
  ONBOARDING_002: '/onboarding/profile',
  EXPENSE_001: '/expenses',
  EXPENSE_002: '/expenses/:id',
  EXPENSE_003: '/expenses/:id/submit',
  EXPENSE_004: '/expenses/scan',
  EXPENSE_005: '/expenses/upload-url',
  MANAGER_001: '/manager/expenses',
  MANAGER_002: '/manager/expenses/:id/approve',
  MANAGER_003: '/manager/expenses/:id/reject',
} as const;