#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════
#  Codespaces / Dev Container — post-create setup
# ════════════════════════════════════════════════════════════════════════
#  Runs once when the container is first built.
#  Goals:
#    1. Materialize a working .env from secrets + reasonable defaults
#    2. Install dependencies for all three services
#    3. Print clear next-step instructions
# ════════════════════════════════════════════════════════════════════════

set -e

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "  FintechSaaS — Dev Container bootstrap"
echo "════════════════════════════════════════════════════════════════════"
echo ""

# ── 1. Generate .env from Codespaces secrets ────────────────────────────
if [ ! -f .env ]; then
  echo "▸ Creating .env from Codespaces Secrets + defaults…"
  cat > .env <<EOF
# Auto-generated by .devcontainer/post-create.sh
# Codespaces injects secrets as env vars; we materialize them into .env
# so docker-compose can read them.

# ── Groq AI ──
GROQ_API_KEY=${GROQ_API_KEY:-}
GROQ_MODEL=llama-3.3-70b-versatile
GROQ_VISION_MODEL=meta-llama/llama-4-scout-17b-16e-instruct

# ── Demo users (passwords come from Codespaces Secrets) ──
DEMO_EMPLOYEE_EMAIL=employee@portfolio.app
DEMO_EMPLOYEE_PASSWORD=${DEMO_EMPLOYEE_PASSWORD:-}
DEMO_MANAGER_EMAIL=manager@portfolio.app
DEMO_MANAGER_PASSWORD=${DEMO_MANAGER_PASSWORD:-}
DEMO_FINANCE_EMAIL=finance@portfolio.app
DEMO_FINANCE_PASSWORD=${DEMO_FINANCE_PASSWORD:-}
DEMO_ADMIN_EMAIL=admin@portfolio.app
DEMO_ADMIN_PASSWORD=${DEMO_ADMIN_PASSWORD:-}

# ── Auth0 / Cognito (intentionally empty for offline demos;
#    populate to use a real tenant) ──
AUTH0_DOMAIN=
AUTH0_CLIENT_ID=
AUTH0_CLIENT_SECRET=
AUTH0_AUDIENCE=

# ── Storage (MinIO defaults — bucket auto-created by docker-compose) ──
B2_ENDPOINT=http://minio:9000
B2_APPLICATION_KEY_ID=minioadmin
B2_APPLICATION_KEY=minioadmin
B2_BUCKET_NAME=receipts
B2_REGION=us-east-1
EOF
  echo "  ✓ .env created"
else
  echo "▸ .env already exists, leaving it alone."
fi

# ── 2. Install dependencies ─────────────────────────────────────────────
echo ""
echo "▸ Installing root npm deps (workspaces helper)…"
npm install --silent || true

echo ""
echo "▸ Installing frontend deps…"
(cd frontend && npm install --silent) || true

echo ""
echo "▸ Installing BFF deps…"
(cd bff && npm install --silent) || true

echo ""
echo "▸ Pre-fetching Maven dependencies (Spring Boot)…"
echo "  (first run takes ~3 minutes, subsequent runs are cached)"
(cd backend && ./mvnw dependency:go-offline -B -q) || true

# ── 3. Next-step instructions ───────────────────────────────────────────
cat <<'BANNER'

════════════════════════════════════════════════════════════════════════
  ✓ Setup complete.

  TO START THE STACK
  ──────────────────
  $  npm run docker:up

  Then click the forwarded port "Nginx Gateway (8080)" in the Ports tab.

  ONE-CLICK DEMO LOGIN
  ────────────────────
  The login page has 4 demo buttons (Employee / Manager / Finance / Admin).
  No credentials needed — those come from the Codespaces Secrets if set.

  TROUBLESHOOTING
  ───────────────
  • Empty queue / no data?  →  docker exec -i mysql mysql -uroot -p12345678 mydb < db_fix.sql
  • OCR returns mock data?  →  Verify GROQ_API_KEY is set in Codespaces Secrets
  • Out of memory?          →  Bump machine size to 4-core / 16 GB

  DOCS
  ────
  README.md                          — Project overview
  docs/expense-lifecycle.md          — 5-state machine, OCR flow, policy snapshot
════════════════════════════════════════════════════════════════════════
BANNER
