spring:
  datasource:
    write:
      url: jdbc:mysql://mysql:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
    read:
      url: jdbc:mysql://mysql:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

groq:
  base-url: https://api.groq.com/openai
  model: ${GROQ_MODEL:llama-3.3-70b-versatile}
  api-key: ${GROQ_API_KEY}
